name: Job

on:
  issue_comment:
    types: [created]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up gost
      run: go install github.com/seiyab/gost/gost@latest

    - name: Print variables
      run: |
        echo ${{ github.event.author.id }}
        echo ${{ github.event.repository.owner.id }}

    - name: Run
      if: ${{ github.event.author.id == github.event.repository.owner.id }}
      run: go run ./ job "${{ github.event.body }}"
        

